name: CI/CD

env:
  AZURE_WEBAPP_NAME: LilaReview

on:
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./api

    permissions:
      contents: read
      packages: write
    
    steps:
    - uses: actions/checkout@v3

    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.19.0'
        cache-dependency-path: ${{github.workspace}}/api/go.sum
    
    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v2
      
    - name: Install Dependencies
      run: |
        go install honnef.co/go/tools/cmd/staticcheck@latest
        go get -v ./...
      
    - name: Build
      run: go build .
      
    - name: Vet & Lint
      run: |
        go vet .
        staticcheck .
      
    - name: Test
      run: go test -v
    
    - name: Log in to Github container registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Lowercase repo name
      run: echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}
    
    - name: Build and push container image to registry
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: ghcr.io/${{ env.REPO }}:${{ github.sha }}
        file: ./api/Dockerfile
  
  deploy:
    runs-on: ubuntu-latest
    needs: [build] 
    
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Lowercase the repo name
        run: echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@85270a1854658d167ab239bce43949edb336fa7c
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          images: 'ghcr.io/${{ env.REPO }}:${{ github.sha }}'