name: Integration

env:
  AZURE_WEBAPP_NAME: LilaReview

on:
  push:
    branches:
    - develop
    - feature/*
    - bugfix/*

jobs:
  build-api:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ${{github.workspace}}/api

    steps:
    - uses: actions/checkout@v3

    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.19.0'
        cache-dependency-path: ${{github.workspace}}/api/go.sum
    
    - name: Install Dependencies
      run: |
        go install honnef.co/go/tools/cmd/staticcheck@latest
        go get -v ./...
      
    - name: Build
      run: |
        go build .
      
    - name: Vet & Lint
      run: |
        go vet .
        staticcheck .
      
    - name: Test
      run: |
        go test -v

  build-ui:
    runs-on: ubuntu-latest

    # defaults:
    #   run:
    #     working-directory: ${{github.workspace}}/ui

    permissions:
      contents: read
      packages: write
    
    steps:
      - name: list directories
        run: ls .

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20.5.0

      - name: Install dependencies
        run: npm ci

      - name: Build React App
        run: npm run build --if-present
    
      - name: Test React App
        run: npm test
