name: Integration

env:
  AZURE_WEBAPP_NAME: LilaReview

on:
  push:
    branches:
    - develop
    - feature/*
    - bugfix/*

jobs:
  build-api:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ${{github.workspace}}/api-rust

    permissions:
      contents: read
      packages: write
    
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt,clippy
      - uses: Swatinem/rust-cache@v2
      
      - name: Run Tests
        run: cargo test
      
      - name: Run fmt
        run: cargo fmt --check

      - name: Linting
        run: cargo clippy -- -D warnings

      - name: Build
        run: cargo build

  build-ui:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ${{github.workspace}}/ui

    permissions:
      contents: read
      packages: write
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20.5.0

      - name: Install dependencies
        run: npm ci

      - name: Build React App
        run: npm run build --if-present
