name: Integration

env:
  AZURE_WEBAPP_NAME: LilaReview

on:
  push:
    branches:
    - develop
  pull_request:
    branches:
    - develop

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
    
    steps:
    - uses: actions/checkout@v3

    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.19.0'
    
    - name: Install Dependencies
      run: |
        go install honnef.co/go/tools/cmd/staticcheck@latest
        go get -v ./...
      
    - name: Build
      run: go build .
      
    - name: Vet & Lint
      run: |
        go vet .
        staticcheck .
      
    - name: Test
      run: go test -v